### ISSUE TITLE
Stop All cause un crash

### ISSUE THREAD

**Issue by sim0504** [RoboCupULaval/StrategyAI#443]
```
Process ai.coach:
Traceback (most recent call last):
  File "/home/simon/Documents/RoboCupProjects/StrategyAI/ai/STA/Strategy/human_control.py", line 22, in assign_tactic
    role = self.game_state.map_player_to_first_available_role(robot_id)
  File "/home/simon/Documents/RoboCupProjects/StrategyAI/ai/states/game_state.py", line 96, in map_player_to_first_available_role
    return self._role_mapper.map_player_to_first_available_role(player)
  File "/home/simon/Documents/RoboCupProjects/StrategyAI/Util/role_mapper.py", line 45, in map_player_to_first_available_role
    raise NoRoleAvailable() from None
Util.role_mapper.NoRoleAvailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/simon/Documents/RoboCupProjects/StrategyAI/ai/coach.py", line 100, in run
    self.main_loop()
  File "/home/simon/Documents/RoboCupProjects/StrategyAI/ai/coach.py", line 113, in main_loop
    self.debug_executor.exec()
  File "/home/simon/Documents/RoboCupProjects/StrategyAI/ai/executors/debug_executor.py", line 27, in exec
    self.play_executor.order_change_of_sta(STAChangeCommand(cmd))
  File "/home/simon/Documents/RoboCupProjects/StrategyAI/ai/executors/play_executor.py", line 74, in order_change_of_sta
    self._change_tactic(cmd)
  File "/home/simon/Documents/RoboCupProjects/StrategyAI/ai/executors/play_executor.py", line 138, in _change_tactic
    self.play_state.current_strategy.assign_tactic(tactic, player_id)
  File "/home/simon/Documents/RoboCupProjects/StrategyAI/ai/STA/Strategy/human_control.py", line 26, in assign_tactic
    self.game_state.map_players_to_roles_by_player_id({role: robot_id})
  File "/home/simon/Documents/RoboCupProjects/StrategyAI/ai/states/game_state.py", line 86, in map_players_to_roles_by_player_id
    for role, player_id in mapping_by_player_id.items()}
  File "/home/simon/Documents/RoboCupProjects/StrategyAI/ai/states/game_state.py", line 86, in <dictcomp>
    for role, player_id in mapping_by_player_id.items()}
KeyError: 6
```

**Comment by sim0504** [comment]
`[INFO ] - PlayExecutor          : You are assigning a tactic to not visible player (id=6).`

**Comment by sim0504** [comment]
patch in #444
